#!/bin/bash

while [ "$1" ]
do
	if [ "$1" = "-i" ]
	then
		input="$2"
		shift 2
	elif [ "$1" = "-o" ]
	then
		output="$2"
		tr a-z A-Z < $input > $output
		cat $output
		shift 2
		continue
	else
		echo "Program $0 does not recognize option $1"
		
	fi
done

